export const metadata = {
  title: 'Help',
}

export default function HelpPage() {
  return (
    <div className="space-y-8">
      <h1 className="section-title">Help &amp; Documentation</h1>

      {/* Overview */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Overview</h2>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          RonaQC is a browser-based quality control tool for SARS-CoV-2 sequencing data.
          It processes BAM files entirely in your browser using WebAssembly — no data is
          uploaded to any server. The tool assesses cross-contamination, primer contamination,
          and consensus sequence quality to determine if samples are reliable for phylogenetic
          analysis and public database submission.
        </p>
      </section>

      {/* Getting Started */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Getting Started</h2>
        <ol className="list-decimal list-inside space-y-2 text-sm text-gx-text-muted leading-relaxed">
          <li>Navigate to the <strong className="text-gx-text">Import</strong> page.</li>
          <li>Select the appropriate <strong className="text-gx-text">ARTIC primer version</strong> used in your sequencing run.</li>
          <li>Optionally toggle <strong className="text-gx-text">subsampling</strong> (recommended for faster processing).</li>
          <li>Upload a <strong className="text-gx-text">negative control</strong> BAM file by dragging it into the drop zone or clicking to browse.</li>
          <li>Upload one or more <strong className="text-gx-text">sample BAM files</strong> in the same way.</li>
          <li>View results on the <strong className="text-gx-text">Control Report</strong> and <strong className="text-gx-text">Sample Report</strong> pages.</li>
        </ol>
      </section>

      {/* File Requirements */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">File Requirements</h2>
        <ul className="list-disc list-inside space-y-1 text-sm text-gx-text-muted leading-relaxed">
          <li>Files must be in <strong className="text-gx-text">BAM format</strong> (.bam extension).</li>
          <li>BAM files should contain reads mapped to the SARS-CoV-2 reference genome (MN908947.3).</li>
          <li>Files generated by ARTIC bioinformatics pipeline are recommended.</li>
          <li>Files larger than 500MB may take a long time to process; files over 2GB are not supported.</li>
        </ul>
      </section>

      {/* Understanding Control Report */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Understanding the Control Report</h2>
        <div className="space-y-4 text-sm text-gx-text-muted leading-relaxed">
          <div>
            <h3 className="font-medium text-gx-text">SNPs</h3>
            <p>Number of single nucleotide polymorphisms detected via ivar variants.
              A good negative control should have <strong className="text-gx-text">0 SNPs</strong>.
              Any SNPs detected indicate potential cross-contamination.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">Called Bases</h3>
            <p>Number of genome positions with coverage &ge;10x.
              A good negative control should have fewer than <strong className="text-gx-text">500 called bases</strong>.
              Values &ge;500 generate a warning.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">Mapped Reads</h3>
            <p>Shows best mapped reads (high-quality, &ge;148bp, MAPQ &ge;60), properly paired reads,
              and total reads. High numbers of mapped reads in a negative control indicate contamination.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">Detected Amplicons</h3>
            <p>Amplicons with &ge;40% coverage. A negative control should have
              <strong className="text-gx-text"> 0 detected amplicons</strong>.
              1 amplicon generates a warning; &gt;1 indicates significant contamination.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">Coverage Plot</h3>
            <p>Shows coverage depth across the SARS-CoV-2 genome. A red line marks the 10x threshold.
              In a clean negative control, coverage should be minimal across the genome.</p>
          </div>
        </div>
      </section>

      {/* Understanding Sample Report */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Understanding the Sample Report</h2>
        <div className="space-y-4 text-sm text-gx-text-muted leading-relaxed">
          <div>
            <h3 className="font-medium text-gx-text">Genome Completeness (Consensus Length)</h3>
            <p>Number of non-N bases in the consensus sequence. The SARS-CoV-2 reference genome (MN908947.3) is 29,903bp.
              Genome completeness is expressed as a percentage of the reference length.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">QC Status</h3>
            <p><strong className="text-gx-success">High QC</strong>: Genome completeness &gt;90%.
               <strong className="text-gx-warning"> Base QC</strong>: Genome completeness &gt;50%.
               <strong className="text-gx-error"> Fail</strong>: Below 50%.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">Judgement</h3>
            <p>An actionable recommendation based on QC results, following{' '}
              <a href="https://github.com/pha4ge/pipeline-resources/blob/main/docs/qc-solutions.md" target="_blank" rel="noopener noreferrer" className="text-gx-accent hover:underline">PHA4GE guidelines</a>:</p>
            <ul className="list-disc list-inside mt-1 space-y-1 pl-2">
              <li><strong className="text-gx-success">Upload</strong> — Suitable for submission to GISAID / INSDC (&gt;90% genome completeness)</li>
              <li><strong className="text-gx-warning">Use only</strong> — Can be used for internal analysis but not for public database submission (50–90%)</li>
              <li><strong className="text-gx-error">Discard</strong> — Insufficient quality for any use (&lt;50%)</li>
            </ul>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">Ambiguous Bases</h3>
            <p>Count of IUPAC ambiguity codes (R, Y, S, W, K, M, B, D, H, V) in the consensus.
              High counts may indicate mixed populations or contamination.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">Longest N Run</h3>
            <p>The longest continuous stretch of N bases in the consensus.
              Long N-runs indicate regions with insufficient coverage.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">Missing Amplicons</h3>
            <p>Count of amplicons with &lt;40% coverage. Missing amplicons cause gaps in the consensus.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">NC Amplicon Cross-Check</h3>
            <p>When a negative control is loaded, amplicons detected in the control are flagged
              in the sample report with a warning badge. This helps identify potential
              cross-contamination at the amplicon level.</p>
          </div>
          <div>
            <h3 className="font-medium text-gx-text">Per-Sample Coverage Plot</h3>
            <p>Click the &quot;Coverage&quot; link in the Actions column to view a genome-wide
              coverage depth plot for each sample.</p>
          </div>
        </div>
      </section>

      {/* QC Guidelines Table (#20) */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">QC Metrics &amp; Thresholds</h2>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          The following table summarises all QC metrics used by RonaQC, their thresholds, and how they
          map to QC status. These guidelines are aligned with{' '}
          <a href="https://github.com/pha4ge/pipeline-resources/blob/main/docs/qc-solutions.md" target="_blank" rel="noopener noreferrer" className="text-gx-accent hover:underline">
            PHA4GE QC recommendations
          </a>.
        </p>
        <div className="overflow-x-auto">
          <table className="gx-table text-sm">
            <thead>
              <tr>
                <th>Metric</th>
                <th>Applies To</th>
                <th>Pass</th>
                <th>Warn</th>
                <th>Fail</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="font-medium">Genome Completeness</td>
                <td>Sample</td>
                <td>&gt;90% (High QC)</td>
                <td>&gt;50% (Base QC)</td>
                <td>&le;50%</td>
              </tr>
              <tr>
                <td className="font-medium">SNPs (Negative Control)</td>
                <td>Control</td>
                <td>0</td>
                <td>&mdash;</td>
                <td>&gt;0</td>
              </tr>
              <tr>
                <td className="font-medium">Called Bases &ge;10x (Control)</td>
                <td>Control</td>
                <td>&lt;500</td>
                <td>&ge;500</td>
                <td>&mdash;</td>
              </tr>
              <tr>
                <td className="font-medium">Detected Amplicons (Control)</td>
                <td>Control</td>
                <td>0</td>
                <td>1</td>
                <td>&gt;1</td>
              </tr>
              <tr>
                <td className="font-medium">Amplicon Coverage</td>
                <td>Sample</td>
                <td>&ge;40%</td>
                <td>&mdash;</td>
                <td>&lt;40% (missing)</td>
              </tr>
              <tr>
                <td className="font-medium">File Size</td>
                <td>Both</td>
                <td>&le;500MB</td>
                <td>500MB &ndash; 2GB</td>
                <td>&gt;2GB (rejected)</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ARTIC Primer Versions */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">ARTIC Primer Versions</h2>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          RonaQC supports ARTIC primer schemes V1 through V4.1. Select the version that matches
          the primers used in your sequencing run. Using the wrong version will produce inaccurate
          amplicon coverage results. V4.1 is the most recent and is selected by default.
        </p>
      </section>

      {/* Subsampling */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Subsampling</h2>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          When enabled, consensus generation subsamples to 30,000 reads. This significantly
          speeds up processing for high-coverage samples without affecting consensus quality.
          Subsampling only applies to samples, not the negative control analysis.
        </p>
      </section>

      {/* Troubleshooting */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Troubleshooting</h2>
        <ul className="list-disc list-inside space-y-1 text-sm text-gx-text-muted leading-relaxed">
          <li><strong className="text-gx-text">Processing seems stuck:</strong> Large BAM files can take several minutes. Check the progress indicator.</li>
          <li><strong className="text-gx-text">Error on upload:</strong> Ensure the file is a valid BAM file, not SAM or FASTQ.</li>
          <li><strong className="text-gx-text">Consensus generation fails:</strong> The BAM file may have too few mapped reads.</li>
          <li><strong className="text-gx-text">Browser runs out of memory:</strong> Try a smaller BAM file or close other browser tabs.</li>
        </ul>
      </section>

      {/* Citation */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Citation</h2>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          If you use RonaQC in your research, please cite the GitHub repository:
        </p>
        <code className="block rounded-lg bg-gx-bg-alt p-3 text-xs font-mono text-gx-text">
          Alikhan, N-F. (2022). RonaQC: Quality control of SARS-CoV-2 genomic data.
          https://github.com/happykhan/ronaQC
        </code>
        <p className="text-sm text-gx-text-muted leading-relaxed mt-2">
          QC terminology and thresholds follow the{' '}
          <a href="https://github.com/pha4ge/pipeline-resources/blob/main/docs/qc-solutions.md" target="_blank" rel="noopener noreferrer" className="text-gx-accent hover:underline">
            PHA4GE SARS-CoV-2 QC guidelines
          </a>.
        </p>
      </section>

      {/* Technology & Privacy */}
      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Technology &amp; Privacy</h2>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          RonaQC runs entirely in your browser using WebAssembly versions of{' '}
          <strong className="text-gx-text">samtools</strong> and{' '}
          <strong className="text-gx-text">ivar</strong> via the{' '}
          <a href="https://biowasm.com" target="_blank" rel="noopener noreferrer" className="text-gx-accent hover:underline">
            biowasm
          </a>{' '}
          project. <strong className="text-gx-text">No data leaves your computer.</strong> All
          processing happens locally — your BAM files are never uploaded to any server.
        </p>
      </section>
    </div>
  )
}
