export function About() {
  return (
    <div className="space-y-8">
      <h1 className="section-title">About RonaQC</h1>

      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">What is RonaQC?</h2>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          RonaQC is a browser-based quality control tool for SARS-CoV-2 sequencing data.
          It accepts mapped reads in BAM format — generated by pipelines such as ARTIC — and
          assesses cross-contamination, primer contamination, and consensus sequence quality to
          determine whether samples are suitable for phylogenetic analysis and submission to
          public databases (GISAID / INSDC).
        </p>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          The tool uses WebAssembly versions of <strong className="text-gx-text">samtools</strong> and{' '}
          <strong className="text-gx-text">ivar</strong> via the{' '}
          <a href="https://biowasm.com" target="_blank" rel="noopener noreferrer" className="text-gx-accent hover:underline">
            biowasm
          </a>{' '}
          project. <strong className="text-gx-text">No data leaves your computer.</strong> All
          processing is performed client-side in the browser.
        </p>

        <div className="rounded-lg border border-gx-info/30 bg-gx-info/10 px-4 py-3 flex items-start gap-3">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-gx-info flex-shrink-0 mt-0.5" aria-hidden="true">
            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
          </svg>
          <p className="text-sm text-gx-text">
            Your BAM files are never uploaded to any server. All analysis happens locally in your browser.
          </p>
        </div>
      </section>

      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Key Features</h2>
        <ul className="list-disc list-inside space-y-2 text-sm text-gx-text-muted leading-relaxed">
          <li>ARTIC primer scheme support (V1 through V5.4.2)</li>
          <li>Negative control QC — detects cross-contamination via SNP and amplicon analysis</li>
          <li>Sample QC — genome completeness, ambiguous bases, longest N run</li>
          <li>Amplicon coverage heatmap for visual QC across samples</li>
          <li>Per-sample genome-wide coverage plots</li>
          <li>Actionable judgements aligned with PHA4GE QC guidelines (Upload / Use only / Discard)</li>
          <li>CSV/TSV export for all reports</li>
          <li>Consensus FASTA download per sample</li>
          <li>Optional subsampling (30K reads) for faster processing</li>
        </ul>
      </section>

      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">About the Author</h2>
        <h3 className="text-base font-semibold text-gx-text">Nabil-Fareed Alikhan</h3>
        <p className="text-sm text-gx-text-muted">
          Senior Bioinformatician, Centre for Genomic Pathogen Surveillance, University of Oxford
        </p>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          Bioinformatics researcher and software developer specialising in microbial genomics.
          Builder of widely used open-source tools, peer-reviewed researcher, and co-host of
          the MicroBinfie podcast.
        </p>
        <div className="flex flex-wrap gap-3 mt-2">
          <a href="https://www.happykhan.com" target="_blank" rel="noopener noreferrer" className="text-sm text-gx-accent hover:text-gx-accent-hover">
            happykhan.com
          </a>
          <a href="https://orcid.org/0000-0002-1243-0767" target="_blank" rel="noopener noreferrer" className="text-sm text-gx-accent hover:text-gx-accent-hover">
            ORCID: 0000-0002-1243-0767
          </a>
          <a href="mailto:nabil@happykhan.com" className="text-sm text-gx-accent hover:text-gx-accent-hover">
            nabil@happykhan.com
          </a>
          <a href="https://twitter.com/happy_khan" target="_blank" rel="noopener noreferrer" className="text-sm text-gx-accent hover:text-gx-accent-hover">
            @happy_khan
          </a>
          <a href="https://mstdn.science/@happykhan" target="_blank" rel="noopener noreferrer" className="text-sm text-gx-accent hover:text-gx-accent-hover">
            @happykhan@mstdn.science
          </a>
        </div>
      </section>

      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Citation</h2>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          If you use RonaQC in your research, please cite:
        </p>
        <code className="block rounded-lg bg-gx-bg-alt p-3 text-xs font-mono text-gx-text">
          Alikhan, N-F. (2022). RonaQC: Quality control of SARS-CoV-2 genomic data.
          https://github.com/happykhan/ronaQC
        </code>
        <p className="text-sm text-gx-text-muted leading-relaxed mt-2">
          QC thresholds follow{' '}
          <a href="https://github.com/pha4ge/pipeline-resources/blob/main/docs/qc-solutions.md" target="_blank" rel="noopener noreferrer" className="text-gx-accent hover:underline">
            PHA4GE SARS-CoV-2 QC guidelines
          </a>.
        </p>
      </section>

      <section className="card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-gx-text">Source Code &amp; License</h2>
        <p className="text-sm text-gx-text-muted leading-relaxed">
          RonaQC is open-source software licensed under the{' '}
          <strong className="text-gx-text">GPL-3.0</strong> licence.
        </p>
        <a
          href="https://github.com/happykhan/ronaQC"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 text-sm text-gx-accent hover:text-gx-accent-hover"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
            <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z" />
          </svg>
          github.com/happykhan/ronaQC
        </a>
      </section>
    </div>
  )
}
