import { Link } from 'react-router-dom'

export function About() {
  return (
    <div className="about-page">
      <section>
        <h2>About RonaQC</h2>
        <p>
          RonaQC is a browser-based quality control tool for SARS-CoV-2 sequencing data.
          It accepts mapped reads in BAM format — generated by pipelines such as ARTIC — and
          assesses cross-contamination, primer contamination, and consensus sequence quality
          to determine whether samples are suitable for phylogenetic analysis and submission
          to public databases (GISAID / INSDC).
        </p>
        <div className="privacy-note">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
          </svg>
          <p>
            Your BAM files are never uploaded to any server. All analysis happens locally
            in your browser using WebAssembly.
          </p>
        </div>
      </section>

      <section>
        <h2>Features</h2>
        <ul>
          <li>ARTIC primer scheme support (V1 through V5.4.2)</li>
          <li>Negative control QC — detects cross-contamination via SNP and amplicon analysis</li>
          <li>Sample QC — genome completeness, ambiguous bases, longest N run</li>
          <li>Amplicon coverage heatmap for visual QC across samples</li>
          <li>Per-sample genome-wide coverage plots</li>
          <li>Actionable judgements aligned with PHA4GE QC guidelines (Upload / Use only / Discard)</li>
          <li>CSV/TSV export for all reports</li>
          <li>Consensus FASTA download per sample</li>
          <li>Optional subsampling (30K reads) for faster processing</li>
        </ul>
      </section>

      <section>
        <h2>How it works</h2>
        <p>
          RonaQC processes each uploaded BAM file using samtools (compiled to WebAssembly)
          to extract coverage statistics and primer site depth. ivar (also WebAssembly) trims
          primer sequences and calls a consensus. The consensus is assessed for completeness,
          ambiguous bases, and longest N run, then an actionable QC call is made following
          PHA4GE guidelines.
        </p>
        <p>
          For negative controls, RonaQC checks for unexpected SNPs and amplicon signal that
          would indicate cross-contamination from positive samples.
        </p>
      </section>

      <section>
        <h2>Technology</h2>
        <ul>
          <li><strong>samtools</strong> — BAM processing and coverage statistics (via biowasm WebAssembly)</li>
          <li><strong>ivar</strong> — primer trimming and consensus calling (via biowasm WebAssembly)</li>
          <li><strong>React + Vite</strong> — frontend framework</li>
          <li><strong>Cloudflare Pages</strong> — global CDN hosting</li>
        </ul>
      </section>

      <section>
        <h2>Citation</h2>
        <p>If you use RonaQC in your research, please cite:</p>
        <blockquote style={{ borderLeft: '4px solid var(--gx-accent)', paddingLeft: '1rem', color: 'var(--gx-text-muted)', fontStyle: 'italic', margin: '0.75rem 0' }}>
          Alikhan, N-F. (2022). RonaQC: Quality control of SARS-CoV-2 genomic data.
          https://github.com/happykhan/ronaQC
        </blockquote>
        <p>
          QC thresholds follow{' '}
          <a href="https://github.com/pha4ge/pipeline-resources/blob/main/docs/qc-solutions.md" target="_blank" rel="noopener noreferrer">
            PHA4GE SARS-CoV-2 QC guidelines
          </a>.
        </p>
      </section>

      <section>
        <h2>Source Code</h2>
        <p>
          RonaQC is open-source software licensed under GPL-3.0. Contributions and issues
          welcome on{' '}
          <a href="https://github.com/happykhan/ronaQC" target="_blank" rel="noopener noreferrer">
            GitHub
          </a>.
        </p>
      </section>

      <section>
        <h2>About the Author</h2>
        <h3>Nabil-Fareed Alikhan</h3>
        <p className="about-role">
          Senior Bioinformatician, Centre for Genomic Pathogen Surveillance, University of Oxford
        </p>
        <p>
          Bioinformatics researcher and software developer specialising in microbial genomics.
          Builder of widely used open-source tools, peer-reviewed researcher, and co-host of
          the MicroBinfie podcast.
        </p>
        <div className="about-links">
          <a href="https://www.happykhan.com" target="_blank" rel="noopener noreferrer">happykhan.com</a>
          <a href="https://orcid.org/0000-0002-1243-0767" target="_blank" rel="noopener noreferrer">ORCID: 0000-0002-1243-0767</a>
          <a href="mailto:nabil@happykhan.com">nabil@happykhan.com</a>
          <a href="https://twitter.com/happy_khan" target="_blank" rel="noopener noreferrer">@happy_khan</a>
          <a href="https://mstdn.science/@happykhan" target="_blank" rel="noopener noreferrer">@happykhan@mstdn.science</a>
        </div>
      </section>

      <div style={{ marginTop: '1rem' }}>
        <Link to="/" style={{ color: 'var(--gx-accent)', textDecoration: 'none', fontWeight: 500 }}>
          ← Back to Application
        </Link>
      </div>
    </div>
  )
}
